# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Juichung Kuo
tagline:          'Kuo' 
description:      'My Website'
url:              http://raymond30031.github.io/
baseurl:          /

author:
  name:           'Juichung Kuo'
  url:            http://raymond30031.github.io/

paginate:         5

plugins: [jekyll-paginate]

# Custom vars
plugins_dir:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - rb-pygments.rb

github:
  repo:           https://github.com/raymond30031/raymond30031.github.io

collections:
  notes:
    output: true
    permalink: /notes/:path/
